name: ChatGPT CodeReviewer
description: 'A Code Review Action Powered By ChatGPT'
branding:
  icon: 'gift'
  color: orange
inputs:
  ANTHROPIC_API_KEY:
    description: 'Anthropic API key or Z.ai key'
    required: true
  ANTHROPIC_BASE_URL:
    description: 'Custom API endpoint'
    required: false
    default: 'https://api.anthropic.com'
runs:
  using: 'node20'
  main: 'action/index.cjs'
